/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

/**
 *
 * @author Dell
 */
public class JFrameCategorias extends javax.swing.JFrame {

    
    public JFrameCategorias() {
        initComponents();
        defineIdioma(JFrameTelaPrincipal.opcao);
    }
    public void defineIdioma(int opcao){
        if (opcao == 1) {
            Selecionar.setText("Select Category");
            jAnimal.setText("Animal");
            jAdjetivo.setText("Adjective");
            jVerbo.setText("Verb");
            jObjeto.setText("Object");
            jComida.setText("Food");
        }
        if (opcao == 2) {
            Selecionar.setText("Choisir une catégorie");
            jAnimal.setText("Animal");
            jAdjetivo.setText("Adjectif");
            jVerbo.setText("Verbe");
            jObjeto.setText("Objet");
            jComida.setText("Nourriture");
        }
        if (opcao == 3) {
            Selecionar.setText("Selecciona una categoría");
            jAnimal.setText("Animal");
            jAdjetivo.setText("Adjetivo");
            jVerbo.setText("Verbo");
            jObjeto.setText("Objeto");
            jComida.setText("Comida");
        }
        if (opcao == 4) {
            Selecionar.setText("Seleziona categoria");
            jAnimal.setText("Animale");
            jAdjetivo.setText("Aggettivo");
            jVerbo.setText("Verbo");
            jObjeto.setText("Oggetto");
            jComida.setText("Cibo");
        }
        if (opcao == 5) {
            Selecionar.setText("Kategorie wählen");
            jAnimal.setText("Tier");
            jAdjetivo.setText("Adjektiv");
            jVerbo.setText("Verb");
            jObjeto.setText("Objekt");
            jComida.setText("Lebensmittel");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selecionar = new javax.swing.JLabel();
        jAdjetivo = new javax.swing.JLabel();
        jButtonAdjetivo = new javax.swing.JButton();
        jAnimal = new javax.swing.JLabel();
        jButtonAnimal = new javax.swing.JButton();
        jComida = new javax.swing.JLabel();
        jButtonComida = new javax.swing.JButton();
        jVerbo = new javax.swing.JLabel();
        jButtonVerbo = new javax.swing.JButton();
        jObjeto = new javax.swing.JLabel();
        jButtonObjeto = new javax.swing.JButton();
        jLabelFundoCat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Selecionar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Selecionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Selecionar);
        Selecionar.setBounds(290, 40, 230, 40);

        jAdjetivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jAdjetivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAdjetivo.setText("jLabel4");
        getContentPane().add(jAdjetivo);
        jAdjetivo.setBounds(110, 120, 100, 30);

        jButtonAdjetivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adjetivo.jpg"))); // NOI18N
        jButtonAdjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdjetivoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdjetivo);
        jButtonAdjetivo.setBounds(110, 160, 100, 100);

        jAnimal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jAnimal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAnimal.setText("jLabel2");
        getContentPane().add(jAnimal);
        jAnimal.setBounds(350, 110, 100, 30);

        jButtonAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/animais.jpg"))); // NOI18N
        jButtonAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnimalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnimal);
        jButtonAnimal.setBounds(330, 150, 150, 120);

        jComida.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jComida.setText("jLabel1");
        getContentPane().add(jComida);
        jComida.setBounds(600, 120, 90, 30);

        jButtonComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/comida.png"))); // NOI18N
        jButtonComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComida);
        jButtonComida.setBounds(580, 150, 140, 100);

        jVerbo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jVerbo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jVerbo.setText("jLabel5");
        getContentPane().add(jVerbo);
        jVerbo.setBounds(480, 310, 80, 30);

        jButtonVerbo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/verbo.jpg"))); // NOI18N
        jButtonVerbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerboActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerbo);
        jButtonVerbo.setBounds(450, 350, 150, 100);

        jObjeto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jObjeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jObjeto.setText("jLabel3");
        getContentPane().add(jObjeto);
        jObjeto.setBounds(220, 300, 120, 30);

        jButtonObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/objeto.jpg"))); // NOI18N
        jButtonObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObjetoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonObjeto);
        jButtonObjeto.setBounds(200, 340, 150, 110);

        jLabelFundoCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela_principal.png"))); // NOI18N
        getContentPane().add(jLabelFundoCat);
        jLabelFundoCat.setBounds(0, 0, 810, 490);

        setSize(new java.awt.Dimension(824, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComidaActionPerformed
        JFramePalpite.idCat = 3;
        JFrameComida tela = new JFrameComida();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonComidaActionPerformed

    private void jButtonAdjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdjetivoActionPerformed
        JFramePalpite.idCat = 1;
        JFrameAdjetivo tela = new JFrameAdjetivo();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonAdjetivoActionPerformed

    private void jButtonVerboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerboActionPerformed
        JFramePalpite.idCat = 5;
        JFrameVerbo tela = new JFrameVerbo();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonVerboActionPerformed

    private void jButtonObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObjetoActionPerformed
        JFramePalpite.idCat = 4;
        JFrameObjeto tela = new JFrameObjeto();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonObjetoActionPerformed

    private void jButtonAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnimalActionPerformed
        JFramePalpite.idCat = 2;
        JFrameAnimal tela = new JFrameAnimal();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Selecionar;
    private javax.swing.JLabel jAdjetivo;
    private javax.swing.JLabel jAnimal;
    private javax.swing.JButton jButtonAdjetivo;
    private javax.swing.JButton jButtonAnimal;
    private javax.swing.JButton jButtonComida;
    private javax.swing.JButton jButtonObjeto;
    private javax.swing.JButton jButtonVerbo;
    private javax.swing.JLabel jComida;
    private javax.swing.JLabel jLabelFundoCat;
    private javax.swing.JLabel jObjeto;
    private javax.swing.JLabel jVerbo;
    // End of variables declaration//GEN-END:variables
}
