/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

/**
 *
 * @author Dell
 */
public class JFrameTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTelaPrincipal
     */
    public JFrameTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selecionar = new javax.swing.JLabel();
        Inglês = new javax.swing.JLabel();
        Francês = new javax.swing.JLabel();
        Espanhol = new javax.swing.JLabel();
        Italiano = new javax.swing.JLabel();
        Alemão = new javax.swing.JLabel();
        jButtonInglaterra = new javax.swing.JButton();
        jButtonFrança = new javax.swing.JButton();
        jButtonEspanha = new javax.swing.JButton();
        jButtonItalia = new javax.swing.JButton();
        jButtonAlemanha = new javax.swing.JButton();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Selecionar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Selecionar.setText("Selecione o idioma para jogar");
        getContentPane().add(Selecionar);
        Selecionar.setBounds(210, 20, 230, 40);

        Inglês.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Inglês.setText("Inglês");
        getContentPane().add(Inglês);
        Inglês.setBounds(90, 70, 110, 40);

        Francês.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Francês.setText("Francês");
        getContentPane().add(Francês);
        Francês.setBounds(280, 70, 110, 40);

        Espanhol.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Espanhol.setText("Espanhol");
        getContentPane().add(Espanhol);
        Espanhol.setBounds(480, 70, 110, 40);

        Italiano.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Italiano.setText("Italiano");
        getContentPane().add(Italiano);
        Italiano.setBounds(180, 230, 110, 40);

        Alemão.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Alemão.setText("Alemão");
        getContentPane().add(Alemão);
        Alemão.setBounds(380, 230, 110, 40);

        jButtonInglaterra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Inglaterra.png"))); // NOI18N
        jButtonInglaterra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInglaterraActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInglaterra);
        jButtonInglaterra.setBounds(50, 110, 116, 69);

        jButtonFrança.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/França.jpg"))); // NOI18N
        jButtonFrança.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrançaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFrança);
        jButtonFrança.setBounds(250, 110, 116, 69);

        jButtonEspanha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Espanha.png"))); // NOI18N
        jButtonEspanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspanhaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEspanha);
        jButtonEspanha.setBounds(450, 110, 116, 69);

        jButtonItalia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Italia.png"))); // NOI18N
        jButtonItalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItaliaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonItalia);
        jButtonItalia.setBounds(150, 270, 116, 69);

        jButtonAlemanha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Alemanha.png"))); // NOI18N
        jButtonAlemanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlemanhaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlemanha);
        jButtonAlemanha.setBounds(350, 270, 116, 69);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela_principal.png"))); // NOI18N
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, 0, 620, 430);

        setSize(new java.awt.Dimension(636, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static int opcao;
    
    private void jButtonInglaterraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInglaterraActionPerformed
        opcao = 1;
        JFrameCategorias tela = new JFrameCategorias();
        tela.setVisible(true);
        
    }//GEN-LAST:event_jButtonInglaterraActionPerformed

    private void jButtonFrançaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrançaActionPerformed
        opcao = 2;
        JFrameCategorias tela = new JFrameCategorias();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonFrançaActionPerformed

    private void jButtonEspanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspanhaActionPerformed
        opcao = 3;
        JFrameCategorias tela = new JFrameCategorias();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonEspanhaActionPerformed

    private void jButtonItaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItaliaActionPerformed
        opcao = 4;
        JFrameCategorias tela = new JFrameCategorias();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonItaliaActionPerformed

    private void jButtonAlemanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlemanhaActionPerformed
        opcao = 5;
        JFrameCategorias tela = new JFrameCategorias();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonAlemanhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alemão;
    private javax.swing.JLabel Espanhol;
    private javax.swing.JLabel Francês;
    private javax.swing.JLabel Inglês;
    private javax.swing.JLabel Italiano;
    private javax.swing.JLabel Selecionar;
    private javax.swing.JButton jButtonAlemanha;
    private javax.swing.JButton jButtonEspanha;
    private javax.swing.JButton jButtonFrança;
    private javax.swing.JButton jButtonInglaterra;
    private javax.swing.JButton jButtonItalia;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
